version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

#  # Diğer mikroservisleriniz burada
#  my-microservice:
#    image: my-app:latest
#    depends_on:
#      - postgres
#    environment:
#      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/myapp_db
#
#volumes:
#  postgres_data: