version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: my_postgres1
    restart: always
    environment:
      POSTGRES_DB: inventory_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data